## Tests and Benchmarks

For each function in the `functions` module, run the Particle Swarm Optimisation (PSO) Algorithm:

- Using the simple algorithm (`PSO()`)

Then do a timing benchmark for `PSO`, `PSO_asynchron`, and `PSO_synchron`.


Default:
- 30 Particles
- At most 500 iterations
- $\epsilon = 10^{-10}$ 
- Search space the same as in the paper.

### A simple quadratic function

$$ f(x) = (x_1 + 2x_2 - 3)^2 + (x_1 - 2)^2$$

In [21]:
from random import seed
seed(1)

In [1]:
# import test function
from functions import quad_function

# import PSO solvers
from PSO import PSO, PSO_synchron, PSO_asynchron

# Basic PSO
solver_basic = PSO(num_particles = 30, function = quad_function, n_iter = 500, ndim = 2,
             lower = -10, upper = 10, epsilon = 10e-10)

solver_basic.run()

Running the PSO algorithm with 30 particles, for at most 500 iterations.

After 72 iterations,
Found minimum at [2.00001122 0.49997214] with value 2.105374063334379e-09.


array([2.00001122, 0.49997214])

In [23]:
# Synchronous Parallel PSO
solver_synchron = PSO_synchron(num_particles = 30, function = quad_function, n_iter = 500, ndim = 2,
                     lower = -10, upper = 10, epsilon = 10e-10)
solver_synchron.run()

Running the PSO algorithm with 30 particles, for at most 500 iterations.

After 98 iterations,
Found minimum at [1.99999743 0.50000528] with value 7.053406317167849e-11.


array([1.99999743, 0.50000528])

In [24]:
# Asynchronous Parallel PSO
solver_asynchron = PSO_asynchron(num_particles = 30, function = quad_function, n_iter = 500, ndim = 2,
                     lower = -10, upper = 10, epsilon = 10e-10)
solver_asynchron.run()

Running the PSO algorithm asynchronously with 30 particles, for at most 15000 function evaluations.

After 2480 function evaluations,
Found minimum at [2.000017881357486, 0.4999867170037465] with value 3.9516583098960784e-10.


[2.000017881357486, 0.4999867170037465]

In [25]:
%timeit -n 10 solver_basic.run(verbose = False)

823 µs ± 81 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
%timeit -n 10 solver_synchron.run(verbose = False)

2.89 ms ± 300 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
%timeit -n 10 solver_asynchron.run(verbose = False)

20.3 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Sphere (de Jong F1)

$$ f(x) = \sum_{i=1}^n x_i^2 $$

In [32]:
from functions import sphere

from PSO import PSO, PSO_synchron, PSO_asynchron

solver_basic = PSO(num_particles = 30, function = sphere, n_iter = 500, ndim = 30,
                     lower = -100, upper = 100, epsilon = 10e-10)
solver_synchron = PSO_synchron(num_particles = 30, function = sphere, n_iter = 500, ndim = 30,
                     lower = -100, upper = 100, epsilon = 10e-10)
solver_asynchron = PSO_asynchron(num_particles = 30, function = sphere, n_iter = 500, ndim = 30,
                     lower = -100, upper = 100, epsilon = 10e-10)


solver_basic.run()
solver_synchron.run()
solver_asynchron.run()

Running the PSO algorithm with 30 particles, for at most 500 iterations.

After 500 iterations,
Found minimum at [-5.84225082e-04  1.64402893e-04 -2.01409219e-04  1.83538405e-03
  3.28197454e-04 -9.28034361e-04 -2.60340331e-05 -7.22516645e-04
  7.16021212e-04 -9.86222975e-04 -5.76872131e-04 -4.60404883e-05
 -1.96787574e-04 -1.56654770e-04 -5.03744672e-04 -3.97601909e-04
  4.01322414e-04  2.87290487e-04  7.00963570e-05  7.32176770e-05
  5.12438676e-04 -2.37492952e-04 -1.41671297e-03 -1.32522905e-03
 -2.74786030e-04 -1.78829318e-03 -1.46532563e-04  1.02593762e-03
 -4.74268918e-04  9.86782565e-04] with value 1.744691657039889e-05.
Running the PSO algorithm with 30 particles, for at most 500 iterations.

After 500 iterations,
Found minimum at [ 0.00119159 -0.00013686 -0.00010047  0.00039365  0.00183527  0.00233277
  0.00743776  0.01038024  0.00200297 -0.00533124  0.00148084 -0.00233423
 -0.00151968 -0.0011107   0.00097095  0.0001555   0.00273366  0.00095513
  0.00028559 -0.00435142 -0.0042

[-0.003585834528523366,
 0.0038254859939985965,
 0.0038943341585532185,
 -0.004266332936761735,
 -0.002595411402103077,
 -0.006285343246076804,
 -0.0010202668018167338,
 0.0020317523147369097,
 -0.0035020548680115824,
 0.0025486812816788926,
 0.004798966314501233,
 0.0030956872649454065,
 -0.00164677931978258,
 0.0015051499683972633,
 0.0068760578973182124,
 6.682715668248143e-05,
 0.003139953089807491,
 -0.002428893185972534,
 0.0017432722126357026,
 0.00518264145219939,
 -0.003397954828873304,
 0.0008026552072486168,
 0.0052571449912408846,
 -0.00244385782813499,
 -0.004117067777594124,
 -0.0014676440796330594,
 -0.0018812578423476182,
 -0.0007028710466846833,
 -0.0018332339667081728,
 -0.0015575899083916241]

Process ForkPoolWorker-857:
Process ForkPoolWorker-858:
Process ForkPoolWorker-856:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/queues.py", line 351, in

In [33]:
%timeit -n 10 solver_basic.run(verbose = False)

The slowest run took 16.56 times longer than the fastest. This could mean that an intermediate result is being cached.
5.8 ms ± 9.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
%timeit -n 10 solver_synchron.run(verbose = False)

The slowest run took 11.86 times longer than the fastest. This could mean that an intermediate result is being cached.
7.97 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [35]:
%timeit -n 10 solver_asynchron.run(verbose = False)

22.3 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### High dimensional Rosenbrock

$${\displaystyle f(\mathbf {x} )=\sum _{i=1}^{N-1}[100(x_{i+1}-x_{i}^{2})^{2}+(1-x_{i})^{2}]\quad {\mbox{where}}\quad \mathbf {x} =[x_{1},\ldots ,x_{N}]\in \mathbb {R} ^{N}.}$$

In [3]:
from functions import high_dim_rosenbrock

In [4]:
# Basic PSO
solver_basic = PSO(num_particles = 30, function = high_dim_rosenbrock, n_iter = 10000, ndim = 30,
             lower = -10, upper = 10, epsilon = 10e-10)
solver_basic.run()

Running the PSO algorithm with 30 particles, for at most 10000 iterations.

After 9064 iterations,
Found minimum at [1.0000096  0.99997279 0.9999881  1.00004525 1.00004111 0.99999569
 1.00001096 0.99998051 1.00001519 0.99997904 1.00001987 0.99997982
 0.9999643  0.99995458 0.99993717 0.99991354 0.99999507 1.00004393
 1.00006177 1.0000646  1.00011528 1.00018393 1.00034907 1.00057355
 1.00113049 1.00218317 1.00426516 1.0085029  1.01699403 1.03437309] with value 0.0003985085508299553.


array([1.0000096 , 0.99997279, 0.9999881 , 1.00004525, 1.00004111,
       0.99999569, 1.00001096, 0.99998051, 1.00001519, 0.99997904,
       1.00001987, 0.99997982, 0.9999643 , 0.99995458, 0.99993717,
       0.99991354, 0.99999507, 1.00004393, 1.00006177, 1.0000646 ,
       1.00011528, 1.00018393, 1.00034907, 1.00057355, 1.00113049,
       1.00218317, 1.00426516, 1.0085029 , 1.01699403, 1.03437309])

In [39]:
solver_asynch = PSO_asynchron(num_particles = 30, function = high_dim_rosenbrock, n_iter = 500, ndim = 30,
             lower = -10, upper = 10, epsilon = 10e-10)
solver_asynch.run()

Running the PSO algorithm asynchronously with 30 particles, for at most 15000 function evaluations.

After 15000 function evaluations,
Found minimum at [0.983928441914591, 0.9694572929261135, 0.9411349937965982, 0.8887048529644176, 0.7947752236428268, 0.6403768722975015, 0.41577832091364336, 0.1781925770272121, 0.022534383339179922, -0.405840737333415, 0.6784882279818124, 0.834740749915203, 0.9168051020378933, 0.9598351141623386, 0.9809702265701783, 0.9889105711887275, 0.9957916614143766, 0.9964444516169165, 0.9967296843062895, 0.997285215284685, 0.9983013167198996, 1.0033923645851204, 1.0133105556387523, 1.0257343074355614, 1.055889395019386, 1.1185013310448317, 1.2550221431749002, 1.5761056403499352, 2.48760675492909, 6.194106149592121] with value 70.60426552719768.


[0.983928441914591,
 0.9694572929261135,
 0.9411349937965982,
 0.8887048529644176,
 0.7947752236428268,
 0.6403768722975015,
 0.41577832091364336,
 0.1781925770272121,
 0.022534383339179922,
 -0.405840737333415,
 0.6784882279818124,
 0.834740749915203,
 0.9168051020378933,
 0.9598351141623386,
 0.9809702265701783,
 0.9889105711887275,
 0.9957916614143766,
 0.9964444516169165,
 0.9967296843062895,
 0.997285215284685,
 0.9983013167198996,
 1.0033923645851204,
 1.0133105556387523,
 1.0257343074355614,
 1.055889395019386,
 1.1185013310448317,
 1.2550221431749002,
 1.5761056403499352,
 2.48760675492909,
 6.194106149592121]

In [44]:
%timeit -n 10 solver_basic.run(verbose = False)

KeyboardInterrupt: 

In [18]:
%timeit -n 10 solver_synchron.run(verbose = False)

3.12 ms ± 844 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
%timeit -n 10 solver_asynch.run(verbose = False)

23.5 ms ± 2.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Griewank function

$$f(x) = 1+{\frac  {1}{4000}}\sum _{{i=1}}^{n}x_{i}^{2}-\prod _{{i=1}}^{n}\cos \left({\frac  {x_{i}}{{\sqrt  {i}}}}\right)$$

In [ ]:
from functions import griewank
# PSO
solver = PSO(num_particles = 60, function = griewank, n_iter = 1000, ndim = 30,
                     lower = -600, upper = 600, epsilon = 10e-07)
solver.run() # acceptable error < 0.1

### Schaffer's F6

$$f(x)=0.5+\frac{sin^2(\sqrt{x_1^2 + x_2^2})-0.5}{[1+0.001 \cdot (x_1^2 + x_2^2)]^2}$$

In [13]:
from functions import schaffer_f6
# PSO
solver = PSO(num_particles = 30, function = schaffer_f6, n_iter = 500, ndim = 2,
                     lower = -100, upper = 100, epsilon = 0)
solver.run() # acceptable error < 10e-06

Running the PSO algorithm with 30 particles, for at most 500 iterations.

After 500 iterations,
Found minimum at [ 2.06203342e-09 -5.34428782e-10] with value 0.0.


array([ 2.06203342e-09, -5.34428782e-10])

### Rastrigin function

$$f(\mathbf {x} )=An+\sum _{i=1}^{n}\left[x_{i}^{2}-A\cos(2\pi x_{i})\right]$$

where $ A=10 $ and $x_{i}\in [-5.12,5.12]$.

In [15]:
from functions import rastrigin
from PSO import *

In [22]:
# PSO
solver = PSO(num_particles = 100, function = rastrigin, n_iter = 200, ndim = 30,
                     lower = -5.12, upper = 5.12, epsilon = 10e-7)
solver.run() # acceptable error < 100

Running the PSO algorithm with 100 particles, for at most 200 iterations.

After 200 iterations,
Found minimum at [-3.37912075e-03 -9.99806333e-01 -7.79087945e-04 -3.98782356e-03
  3.97690808e+00 -1.98021112e+00  9.92264219e-01 -9.91646932e-01
  3.00307949e+00 -1.00766522e+00  4.37998632e-03 -2.84200162e-03
 -9.96185333e-01 -5.19562497e-03  1.98806938e+00  1.31949995e-02
  1.98504280e+00 -9.93752794e-01  5.50782026e-03 -1.01028071e+00
  1.98558980e+00 -9.95610633e-01  9.85252905e-01  9.93786347e-01
 -1.00547710e+00  9.63235475e-03 -9.94820310e-01 -7.66437141e-03
  9.87950984e-01  1.00638266e+00] with value 55.06857957681086.


array([-3.37912075e-03, -9.99806333e-01, -7.79087945e-04, -3.98782356e-03,
        3.97690808e+00, -1.98021112e+00,  9.92264219e-01, -9.91646932e-01,
        3.00307949e+00, -1.00766522e+00,  4.37998632e-03, -2.84200162e-03,
       -9.96185333e-01, -5.19562497e-03,  1.98806938e+00,  1.31949995e-02,
        1.98504280e+00, -9.93752794e-01,  5.50782026e-03, -1.01028071e+00,
        1.98558980e+00, -9.95610633e-01,  9.85252905e-01,  9.93786347e-01,
       -1.00547710e+00,  9.63235475e-03, -9.94820310e-01, -7.66437141e-03,
        9.87950984e-01,  1.00638266e+00])

In [24]:
# Asynchronous Parallel PSO
solver_asynchron = PSO_asynchron(num_particles = 100, function = rastrigin, n_iter = 200, ndim = 30,
                     lower = -5.12, upper = 5.12, epsilon = 10e-16)
solver_asynchron.run() # acceptable error < 100

Running the PSO algorithm asynchronously with 100 particles, for at most 20000 function evaluations.

After 19956 function evaluations,
Found minimum at [-1.9851162236310642, -0.9767254839377012, 0.9681459721312682, 1.097397219395972, -1.9323300862347008, -2.0192960890025926, -1.0122491045245257, -1.993480616989867, -0.032249567001426206, 0.9765540468373101, 1.9371882977701196, -0.02016073179963001, -0.9557577115537138, 1.006519611884433, -0.027312071363085007, -0.11712356588798922, 0.02290108085190998, -0.022177058554074407, -1.1000014542898198, 0.942627788822151, 1.9841674335212967, 0.014242713803483874, 0.04048718244064234, -0.09653822356070726, -0.08976622876535562, 1.9618000336711567, 2.011926755240875, -1.9631256176461458, 0.003920862652325295, 1.0464331949366552] with value 60.35604329125468.


[-1.9851162236310642,
 -0.9767254839377012,
 0.9681459721312682,
 1.097397219395972,
 -1.9323300862347008,
 -2.0192960890025926,
 -1.0122491045245257,
 -1.993480616989867,
 -0.032249567001426206,
 0.9765540468373101,
 1.9371882977701196,
 -0.02016073179963001,
 -0.9557577115537138,
 1.006519611884433,
 -0.027312071363085007,
 -0.11712356588798922,
 0.02290108085190998,
 -0.022177058554074407,
 -1.1000014542898198,
 0.942627788822151,
 1.9841674335212967,
 0.014242713803483874,
 0.04048718244064234,
 -0.09653822356070726,
 -0.08976622876535562,
 1.9618000336711567,
 2.011926755240875,
 -1.9631256176461458,
 0.003920862652325295,
 1.0464331949366552]

In [ ]:
import numpy as np
np.array([1, 2]) * np.array([1, 1])