## Tests and Benchmarks

For each function in the `functions` module, run the Particle Swarm Optimisation (PSO) Algorithm:

- Using the simple algorithm (`PSO()`)
- Synchronous parallel (`PSO_synchron()`)
- Asynchronous parallel (`PSO_asynchron()`)
    

### A simple quadratic function

$$ f(x) = (x_1 + 2x_2 - 3)^2 + (x_1 - 2)^2$$

In [1]:
# import test function
from functions import quad_function

# import PSO solvers
from PSO import PSO, PSO_synchron, PSO_asynchron

# Basic PSO
solver_basic = PSO(num_particles = 20, function = quad_function, n_iter = 200, ndim = 2,
             lower = -10, upper = 10, epsilon = 10e-10)
solver_basic.run()

Running the PSO algorithm with 20 particles, for at most 200 iterations.

After 88 iterations,
Found minimum at [1.99997289 0.50002268] with value 1.0678849816437163e-09.


array([1.99997289, 0.50002268])

In [2]:
# Synchronous Parallel PSO
solver_synchron = PSO_synchron(num_particles = 20, function = quad_function, n_iter = 200, ndim = 2,
                     lower = -10, upper = 10, epsilon = 10e-10)
solver_synchron.run()

Running the PSO algorithm with 20 particles, for at most 200 iterations.

After 81 iterations,
Found minimum at [2.00001266 0.49999725] with value 2.117457513424202e-10.


array([2.00001266, 0.49999725])

Process ForkPoolWorker-3:
Process ForkPoolWorker-2:
Process ForkPoolWorker-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/home/vincent/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker


In [3]:
# Asynchronous Parallel PSO
solver_asynchron = PSO_asynchron(num_particles = 20, function = quad_function, n_iter = 200, ndim = 2,
                     lower = -10, upper = 10, epsilon = 10e-10)
solver_asynchron.run()

Running the PSO algorithm asynchronously with 20 particles, for at most 4000 function evaluations.

After 1526 function evaluations,
Found minimum at [2.000072770216814, 0.4999611979074011] with value 5.3188717055179754e-09.


[2.000072770216814, 0.4999611979074011]

In [ ]:
%time solver_basic.run(verbose = False)

In [ ]:
%time solver_synchron.run(verbose = False)

In [ ]:
%time solver_asynchron.run(verbose = False)

### Sphere (de Jong F1)

$$ f(x) = \sum_{i=1}^n x_i^2 $$

In [7]:
from functions import sphere
# import PSO solvers
from PSO import PSO, PSO_synchron, PSO_asynchron

solver = PSO(num_particles = 30, function = sphere, n_iter = 500, ndim = 30,
                     lower = -10, upper = 10, epsilon = 10e-07)
solver.run() # better defaults are needed...

Running the PSO algorithm with 30 particles, for at most 500 iterations.

After 362 iterations,
Found minimum at [-1.27452896e-05  3.48098836e-04 -1.80727385e-03 -7.62988774e-04
 -4.12380260e-04 -6.27375582e-04  1.95585906e-03  1.11120040e-03
 -5.48996119e-04 -1.07758811e-03  1.63254568e-03 -1.78365638e-03
  3.43013521e-03 -2.15728526e-03  7.45222014e-04 -8.82634269e-06
  7.19772784e-04  1.32149703e-03 -1.91601945e-03 -4.83722481e-04
 -1.35832496e-03 -3.09537007e-04 -3.35637708e-04 -1.23980040e-04
 -8.36521257e-04  2.91237694e-04 -6.92423713e-04  6.38792483e-04
 -2.59414709e-03  3.86815699e-04] with value 5.066765176672013e-05.


array([-1.27452896e-05,  3.48098836e-04, -1.80727385e-03, -7.62988774e-04,
       -4.12380260e-04, -6.27375582e-04,  1.95585906e-03,  1.11120040e-03,
       -5.48996119e-04, -1.07758811e-03,  1.63254568e-03, -1.78365638e-03,
        3.43013521e-03, -2.15728526e-03,  7.45222014e-04, -8.82634269e-06,
        7.19772784e-04,  1.32149703e-03, -1.91601945e-03, -4.83722481e-04,
       -1.35832496e-03, -3.09537007e-04, -3.35637708e-04, -1.23980040e-04,
       -8.36521257e-04,  2.91237694e-04, -6.92423713e-04,  6.38792483e-04,
       -2.59414709e-03,  3.86815699e-04])

### High dimensional Rosenbrock

$${\displaystyle f(\mathbf {x} )=\sum _{i=1}^{N-1}[100(x_{i+1}-x_{i}^{2})^{2}+(1-x_{i})^{2}]\quad {\mbox{where}}\quad \mathbf {x} =[x_{1},\ldots ,x_{N}]\in \mathbb {R} ^{N}.}$$

In [8]:
from functions import high_dim_rosenbrock

In [9]:
# Basic PSO
solver_basic = PSO(num_particles = 20, function = high_dim_rosenbrock, n_iter = 500, ndim = 30,
             lower = -10, upper = 10, epsilon = 10e-7)
solver_basic.run()

Running the PSO algorithm with 20 particles, for at most 500 iterations.

After 500 iterations,
Found minimum at [ 0.9945954   0.97431422  0.96171955  0.93747333  0.88059006  0.76436351
  0.57761664  0.38603644  0.18364365  0.05065528  0.00332958  0.02279276
  0.03136523  0.05210733  0.03211644  0.00638433  0.01619091 -0.0060635
  0.0053486   0.01328082  0.00480944  0.0221323   0.0126366  -0.0110851
  0.02708078  0.00681679  0.02879423  0.00287449  0.02090426 -0.00278394] with value 21.948210881439845.


array([ 0.9945954 ,  0.97431422,  0.96171955,  0.93747333,  0.88059006,
        0.76436351,  0.57761664,  0.38603644,  0.18364365,  0.05065528,
        0.00332958,  0.02279276,  0.03136523,  0.05210733,  0.03211644,
        0.00638433,  0.01619091, -0.0060635 ,  0.0053486 ,  0.01328082,
        0.00480944,  0.0221323 ,  0.0126366 , -0.0110851 ,  0.02708078,
        0.00681679,  0.02879423,  0.00287449,  0.02090426, -0.00278394])

In [11]:
solver_asynch = PSO_asynchron(num_particles = 30, function = high_dim_rosenbrock, n_iter = 500, ndim = 30,
             lower = -10, upper = 10, epsilon = 0)
solver_asynch.run()

Running the PSO algorithm asynchronously with 30 particles, for at most 15000 function evaluations.

After 14998 function evaluations,
Found minimum at [0.7997719280605541, 0.634072686828475, 0.40461647746324353, 0.16442957512634582, 0.021692843912095756, 0.014002548740222581, 0.018103061949471366, 0.009582665589749757, 0.009662836334067946, 0.013037712113991564, 0.01133378647145314, 0.0132951453470765, 0.014182591025788914, 0.014795646171358715, 0.0841708593837759, 0.4391035573909605, 0.6792792126926804, 0.8215003037970681, 0.8882060848956767, 0.9158705281162081, 0.9109273651555485, 0.8669371760463659, 0.8034188814608104, 0.683931623255457, 0.4934894395464813, 0.2536871200195855, 0.07198743282420918, 0.011660819520653504, 0.011835562960356105, -0.002161787688488191] with value 79.54977017323763.


[0.7997719280605541,
 0.634072686828475,
 0.40461647746324353,
 0.16442957512634582,
 0.021692843912095756,
 0.014002548740222581,
 0.018103061949471366,
 0.009582665589749757,
 0.009662836334067946,
 0.013037712113991564,
 0.01133378647145314,
 0.0132951453470765,
 0.014182591025788914,
 0.014795646171358715,
 0.0841708593837759,
 0.4391035573909605,
 0.6792792126926804,
 0.8215003037970681,
 0.8882060848956767,
 0.9158705281162081,
 0.9109273651555485,
 0.8669371760463659,
 0.8034188814608104,
 0.683931623255457,
 0.4934894395464813,
 0.2536871200195855,
 0.07198743282420918,
 0.011660819520653504,
 0.011835562960356105,
 -0.002161787688488191]

### Griewank function

$$f(x) = 1+{\frac  {1}{4000}}\sum _{{i=1}}^{n}x_{i}^{2}-\prod _{{i=1}}^{n}\cos \left({\frac  {x_{i}}{{\sqrt  {i}}}}\right)$$

In [ ]:
from functions import griewank
# PSO
solver = PSO(num_particles = 60, function = griewank, n_iter = 1000, ndim = 30,
                     lower = -600, upper = 600, epsilon = 10e-07)
solver.run() # acceptable error < 0.1

### Schaffer's F6

$$f(x)=0.5+\frac{sin^2(\sqrt{x_1^2 + x_2^2})-0.5}{[1+0.001 \cdot (x_1^2 + x_2^2)]^2}$$

In [13]:
from functions import schaffer_f6
# PSO
solver = PSO(num_particles = 30, function = schaffer_f6, n_iter = 500, ndim = 2,
                     lower = -100, upper = 100, epsilon = 0)
solver.run() # acceptable error < 10e-06

Running the PSO algorithm with 30 particles, for at most 500 iterations.

After 500 iterations,
Found minimum at [ 2.06203342e-09 -5.34428782e-10] with value 0.0.


array([ 2.06203342e-09, -5.34428782e-10])

### Rastrigin function

$$f(\mathbf {x} )=An+\sum _{i=1}^{n}\left[x_{i}^{2}-A\cos(2\pi x_{i})\right]$$

where $ A=10 $ and $x_{i}\in [-5.12,5.12]$.

In [15]:
from functions import rastrigin
from PSO import *

In [22]:
# PSO
solver = PSO(num_particles = 100, function = rastrigin, n_iter = 200, ndim = 30,
                     lower = -5.12, upper = 5.12, epsilon = 10e-7)
solver.run() # acceptable error < 100

Running the PSO algorithm with 100 particles, for at most 200 iterations.

After 200 iterations,
Found minimum at [-3.37912075e-03 -9.99806333e-01 -7.79087945e-04 -3.98782356e-03
  3.97690808e+00 -1.98021112e+00  9.92264219e-01 -9.91646932e-01
  3.00307949e+00 -1.00766522e+00  4.37998632e-03 -2.84200162e-03
 -9.96185333e-01 -5.19562497e-03  1.98806938e+00  1.31949995e-02
  1.98504280e+00 -9.93752794e-01  5.50782026e-03 -1.01028071e+00
  1.98558980e+00 -9.95610633e-01  9.85252905e-01  9.93786347e-01
 -1.00547710e+00  9.63235475e-03 -9.94820310e-01 -7.66437141e-03
  9.87950984e-01  1.00638266e+00] with value 55.06857957681086.


array([-3.37912075e-03, -9.99806333e-01, -7.79087945e-04, -3.98782356e-03,
        3.97690808e+00, -1.98021112e+00,  9.92264219e-01, -9.91646932e-01,
        3.00307949e+00, -1.00766522e+00,  4.37998632e-03, -2.84200162e-03,
       -9.96185333e-01, -5.19562497e-03,  1.98806938e+00,  1.31949995e-02,
        1.98504280e+00, -9.93752794e-01,  5.50782026e-03, -1.01028071e+00,
        1.98558980e+00, -9.95610633e-01,  9.85252905e-01,  9.93786347e-01,
       -1.00547710e+00,  9.63235475e-03, -9.94820310e-01, -7.66437141e-03,
        9.87950984e-01,  1.00638266e+00])

In [24]:
# Asynchronous Parallel PSO
solver_asynchron = PSO_asynchron(num_particles = 100, function = rastrigin, n_iter = 200, ndim = 30,
                     lower = -5.12, upper = 5.12, epsilon = 10e-16)
solver_asynchron.run() # acceptable error < 100

Running the PSO algorithm asynchronously with 100 particles, for at most 20000 function evaluations.

After 19956 function evaluations,
Found minimum at [-1.9851162236310642, -0.9767254839377012, 0.9681459721312682, 1.097397219395972, -1.9323300862347008, -2.0192960890025926, -1.0122491045245257, -1.993480616989867, -0.032249567001426206, 0.9765540468373101, 1.9371882977701196, -0.02016073179963001, -0.9557577115537138, 1.006519611884433, -0.027312071363085007, -0.11712356588798922, 0.02290108085190998, -0.022177058554074407, -1.1000014542898198, 0.942627788822151, 1.9841674335212967, 0.014242713803483874, 0.04048718244064234, -0.09653822356070726, -0.08976622876535562, 1.9618000336711567, 2.011926755240875, -1.9631256176461458, 0.003920862652325295, 1.0464331949366552] with value 60.35604329125468.


[-1.9851162236310642,
 -0.9767254839377012,
 0.9681459721312682,
 1.097397219395972,
 -1.9323300862347008,
 -2.0192960890025926,
 -1.0122491045245257,
 -1.993480616989867,
 -0.032249567001426206,
 0.9765540468373101,
 1.9371882977701196,
 -0.02016073179963001,
 -0.9557577115537138,
 1.006519611884433,
 -0.027312071363085007,
 -0.11712356588798922,
 0.02290108085190998,
 -0.022177058554074407,
 -1.1000014542898198,
 0.942627788822151,
 1.9841674335212967,
 0.014242713803483874,
 0.04048718244064234,
 -0.09653822356070726,
 -0.08976622876535562,
 1.9618000336711567,
 2.011926755240875,
 -1.9631256176461458,
 0.003920862652325295,
 1.0464331949366552]

In [ ]:
import numpy as np
np.array([1, 2]) * np.array([1, 1])